<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ocyfrovka.Core\Ocyfrovka.Core.csproj" />
    <ProjectReference Include="..\Ocyfrovka.Layout\Ocyfrovka.Layout.csproj" />
  </ItemGroup>
</Project>
